"""
UCI configuration script generator for OpenWrt mesh routers.
Generates /etc/uci-defaults/ scripts for auto-configuration.
"""

from typing import Optional
import ipaddress


class UCIGenerator:
    """
    UCI configuration script generator.

    Generates shell scripts that configure OpenWrt routers using UCI commands.
    Based on the mesh network auto-configuration requirements.
    """

    def __init__(
        self,
        router_ip: str,
        dhcp_pool_start: str,
        dhcp_pool_end: str,
        network_cidr: str,
        infrastructure_cidr: str,
        mesh_ssid: str,
        mesh_password: str = "",
        clients_per_router: int = 126,
        babel_port: int = 33123,
        client_ssid: Optional[str] = None,
        client_password: Optional[str] = None,
        client_encryption: str = "none",
    ):
        self.router_ip = router_ip
        self.dhcp_pool_start = dhcp_pool_start
        self.dhcp_pool_end = dhcp_pool_end
        self.network_cidr = network_cidr
        self.infrastructure_cidr = infrastructure_cidr
        self.mesh_ssid = mesh_ssid
        self.mesh_password = mesh_password
        self.clients_per_router = clients_per_router
        self.babel_port = babel_port
        self.client_ssid = client_ssid
        self.client_password = client_password
        self.client_encryption = client_encryption

        # Calculate netmask
        network = ipaddress.IPv4Network(network_cidr)
        self.netmask = str(network.netmask)

    def generate(self) -> str:
        """
        Generate complete UCI defaults script.

        Returns:
            Shell script content for /etc/uci-defaults/99-openmesh-config
        """
        script = f"""#!/bin/sh
# OpenMesh Auto-Configuration Script
# Generated by OpenMesh Platform
#
# This script configures a mesh router with:
# - Router IP: {self.router_ip}
# - DHCP Pool: {self.dhcp_pool_start} - {self.dhcp_pool_end}
# - Mesh SSID: {self.mesh_ssid}
# - Network: {self.network_cidr}
# - Infrastructure: {self.infrastructure_cidr}

# Exit on error
set -e

echo "OpenMesh: Starting auto-configuration..."

#
# 1. Configure LAN Interface
#
echo "OpenMesh: Configuring LAN interface..."

# Set static IP address for LAN
uci set network.lan.proto='static'
uci set network.lan.ipaddr='{self.router_ip}'
uci set network.lan.netmask='{self.netmask}'

# Disable IPv6 DHCP on LAN (optional)
uci set network.lan.ip6assign=''

#
# 2. Configure DHCP Server
#
echo "OpenMesh: Configuring DHCP server..."

# Set DHCP pool range
uci set dhcp.lan.start='{self._get_dhcp_start_offset()}'
uci set dhcp.lan.limit='{self.clients_per_router}'
uci set dhcp.lan.leasetime='12h'

# Enable DHCP server
uci set dhcp.lan.ignore='0'

#
# 3. Install Babel Routing Protocol
#
echo "OpenMesh: Configuring Babel routing..."

# Ensure babeld is installed (should be in image)
opkg list-installed | grep -q babeld || opkg update && opkg install babeld

# Configure Babel
uci set babeld.general=general
uci set babeld.general.export_table='254'
uci set babeld.general.import_table='254'
uci set babeld.general.local_server='33123'
uci set babeld.general.log_file='/var/log/babeld.log'

# Configure Babel on LAN interface (bridge)
uci set babeld.lan=interface
uci set babeld.lan.ifname='br-lan'
uci set babeld.lan.type='wired'
uci set babeld.lan.rxcost='96'

# Configure Babel redistribution (CRITICAL: only infrastructure)
uci set babeld.redistribute=filter
uci set babeld.redistribute.type='redistribute'
uci set babeld.redistribute.ip='{self.infrastructure_cidr}'
uci set babeld.redistribute.action='metric 128'

# Deny redistribution of client pools
uci set babeld.deny_clients=filter
uci set babeld.deny_clients.type='redistribute'
uci set babeld.deny_clients.action='deny'

# Enable Babel daemon
uci set babeld.general.enabled='1'

#
# 4. Configure Mesh WiFi (Ad-hoc)
#
echo "OpenMesh: Configuring mesh WiFi..."

# Get first WiFi radio
RADIO=$(uci show wireless | grep 'wifi-device' | head -n 1 | cut -d. -f2 | cut -d= -f1)

if [ -n "$RADIO" ]; then
    # Enable radio
    uci set wireless.${{RADIO}}.disabled='0'
    uci set wireless.${{RADIO}}.country='US'
    uci set wireless.${{RADIO}}.channel='auto'

    # Create mesh interface
    uci set wireless.mesh=wifi-iface
    uci set wireless.mesh.device="$RADIO"
    uci set wireless.mesh.mode='adhoc'
    uci set wireless.mesh.ssid='{self.mesh_ssid}'
    uci set wireless.mesh.network='lan'
    uci set wireless.mesh.encryption='none'
    uci set wireless.mesh.bssid='02:CA:FE:F0:00:01'  # Common BSSID for mesh

    # Set mesh parameters
    uci set wireless.mesh.mcast_rate='24000'

    echo "OpenMesh: Mesh WiFi configured on radio $RADIO"
else
    echo "OpenMesh: WARNING - No WiFi radio found, skipping mesh WiFi setup"
fi
"""

        # Add client AP interface if client_ssid is provided
        if self.client_ssid:
            script += f"""
#
# Client Access Point Interface
#
echo "OpenMesh: Configuring client AP..."

if [ -n "$RADIO" ]; then
    # Create client AP interface on same radio (virtual interface)
    uci set wireless.client_ap=wifi-iface
    uci set wireless.client_ap.device="$RADIO"
    uci set wireless.client_ap.mode='ap'
    uci set wireless.client_ap.ssid='{self.client_ssid}'
    uci set wireless.client_ap.network='lan'
    uci set wireless.client_ap.encryption='{self.client_encryption}'
"""

            # Add password if encryption is enabled
            if self.client_encryption != 'none' and self.client_password:
                script += f"    uci set wireless.client_ap.key='{self.client_password}'\n"

            script += """
    echo "OpenMesh: Client AP configured on radio $RADIO"
else
    echo "OpenMesh: WARNING - No WiFi radio found, skipping client AP setup"
fi
"""

        script += """
#
# 5. Configure Firewall
#
echo "OpenMesh: Configuring firewall..."

# Allow Babel on LAN
uci set firewall.babel=rule
uci set firewall.babel.name='Allow-Babel'
uci set firewall.babel.src='lan'
uci set firewall.babel.dest_port='6696'
uci set firewall.babel.proto='udp'
uci set firewall.babel.target='ACCEPT'

# Allow Babel local server
uci set firewall.babel_local=rule
uci set firewall.babel_local.name='Allow-Babel-Local'
uci set firewall.babel_local.src='lan'
uci set firewall.babel_local.dest_port='{self.babel_port}'
uci set firewall.babel_local.proto='tcp'
uci set firewall.babel_local.target='ACCEPT'

#
# 6. Commit All Changes
#
echo "OpenMesh: Committing configuration..."

uci commit network
uci commit dhcp
uci commit babeld
uci commit wireless
uci commit firewall

#
# 7. Restart Services
#
echo "OpenMesh: Restarting services..."

/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/babeld enable
/etc/init.d/babeld start
/etc/init.d/firewall restart

# Restart WiFi (delayed to ensure network is up)
sleep 5
wifi

echo "OpenMesh: Auto-configuration complete!"
echo "OpenMesh: Router IP: {self.router_ip}"
echo "OpenMesh: DHCP Pool: {self.dhcp_pool_start} - {self.dhcp_pool_end}"
echo "OpenMesh: Mesh SSID: {self.mesh_ssid}"

# Report to OpenMesh platform (if reachable)
# This will be implemented later with proper authentication
# curl -X POST http://platform/api/v1/devices/register \\
#   -H "Content-Type: application/json" \\
#   -d "{{...device info...}}"

# Self-delete this script
rm -f /etc/uci-defaults/99-openmesh-config

exit 0
"""
        return script

    def _get_dhcp_start_offset(self) -> int:
        """
        Calculate DHCP start offset within subnet.

        Returns:
            Start offset (e.g., 1 for pool starting at .1)
        """
        pool_start_ip = ipaddress.IPv4Address(self.dhcp_pool_start)
        # Get last octet (e.g., .1 -> 1, .127 -> 127)
        return int(pool_start_ip) & 0xFF

    def generate_minimal(self) -> str:
        """
        Generate minimal configuration script (for testing).

        Returns:
            Minimal shell script
        """
        return f"""#!/bin/sh
# OpenMesh Minimal Configuration

uci set network.lan.ipaddr='{self.router_ip}'
uci set network.lan.netmask='{self.netmask}'
uci commit network
/etc/init.d/network restart

echo "Configured: IP={self.router_ip}"
rm -f /etc/uci-defaults/99-openmesh-config
"""
